{
 "title": "Airflow Demo - Covid 19 Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "query": "SELECT country FROM country_based GROUP BY country ORDER BY country ASC;"
   }
  ]
 },
 "panels": [
  { "title": "Region Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Confirmed Case",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  updated AS \"time\",\n  SUM(confirmed) AS metric,\n  latitude,\n  longitude,\n  region\nFROM regional_based\nWHERE\n  $__timeFilter(updated)\nGROUP BY region, latitude, longitude\nORDER BY updated"
    }
   ]
  },
  {
   "title": "Confirmed Case - Top 10 Region",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  region,\n  SUM(confirmed) AS metric\nFROM regional_based\nWHERE\n  $__timeFilter(updated)\nGROUP BY region\nORDER BY metric DESC\nLIMIT 0,10"
    }
   ]
  },
  {
   "title": "Death Case",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  updated AS \"time\",\n  SUM(death) AS metric,\n  latitude,\n  longitude,\n  region\nFROM regional_based\nWHERE\n  $__timeFilter(updated)\nGROUP BY region, latitude, longitude\nORDER BY updated"
    }
   ]
  },
  {
   "title": "Death Case Today - Top 10 Region",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  region,\n  SUM(death) AS metric\nFROM regional_based\nWHERE\n  $__timeFilter(updated)\nGROUP BY region\nORDER BY metric DESC\nLIMIT 0,10"
    }
   ]
  },
  { "title": "Trends of Selected Country", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cases Trending",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  updated AS \"time\",\n  confirmed AS metric\nFROM country_based\nWHERE\n  $__timeFilter(updated) AND\n  country = '$country'\nORDER BY updated"
    },
    {
     "rawSql": "SELECT\n  updated AS \"time\",\n  death AS metric\nFROM country_based\nWHERE\n  $__timeFilter(updated) AND\n  country = '$country'\nORDER BY updated"
    }
   ]
  }
 ]
}